client_id = "82eced5aa9bfae29ddbed3423bf2031e"
name = "Floating Menu 2026"
application_url = "https://floating-menu-app.onrender.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[access_scopes]
scopes = ""

[auth]
redirect_urls = [ "https://floating-menu-app.onrender.com/api/auth/callback" ]

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "https://floating-menu-app.onrender.com/api/webhooks"

[[webhooks.subscriptions]]
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact"
]
uri = "https://floating-menu-app.onrender.com/api/webhooks"